# Generated by Django 2.2.3 on 2019-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(default='', max_length=1000)),
                ('site_name', models.CharField(default='', max_length=1000)),
                ('site_long', models.CharField(default='', max_length=1000)),
                ('site_lat', models.CharField(default='', max_length=1000)),
                ('site_weight', models.CharField(default='', max_length=1000)),
                ('site_status', models.CharField(default='', max_length=1000)),
                ('site_E', models.CharField(default='', max_length=1000)),
                ('site_Eby', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
