# Generated by Django 2.2.3 on 2019-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_A', models.CharField(default='', max_length=1000)),
                ('site_B', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
