# Generated by Django 3.1.6 on 2021-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_map',
            name='site_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='site_map',
            name='site_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
