# Generated by Django 3.1.6 on 2021-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210918_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteA', models.IntegerField()),
                ('siteB', models.IntegerField()),
                ('link_name', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
