# Generated by Django 4.0.3 on 2022-04-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_remove_links_sitea_links_sitea_remove_links_siteb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='siteA',
        ),
        migrations.AddField(
            model_name='links',
            name='siteA',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SiteA', to='links.site_map'),
        ),
        migrations.RemoveField(
            model_name='links',
            name='siteB',
        ),
        migrations.AddField(
            model_name='links',
            name='siteB',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='SiteB', to='links.site_map'),
        ),
    ]
